// <auto-generated />
namespace AspDotNetMvcCodeFirstProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mgr0001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mgr0001));
        
        string IMigrationMetadata.Id
        {
            get { return "202111170427285_Mgr0001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
